backend:
  container_name: open_loyalty_backend
  build: ./backend
  links:
    - elk
    - db
    - mail
  command: bash -c "composer install -o --prefer-dist && bin/console assets:install --symlink && chown -R www-data:www-data /var/www/ol/backend/var && apache2-foreground"
  ports:
    - "8181:80"
  extra_hosts:
    - "web:127.0.0.1"
frontend:
  container_name: open_loyalty_frontend
  build: ./frontend
  ports:
    - "8182:3000"
    - "8183:3001"
    - "8184:3002"
elk:
  container_name: open_loyalty_elk
  image: elasticsearch:2.2
  volumes:
    - ./esdata:/usr/share/elasticsearch/data
db:
  container_name: open_loyalty_postgresql
  image: postgres
  volumes:
    - ./postgres_data:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=openloyalty
    - POSTGRES_USER=openloyalty
    - POSTGRES_PASSWORD=openloyalty
mail:
  image: mailhog/mailhog
  ports:
    - "8186:8025"
