services:
  backend:
    container_name: open_loyalty_backend_dev
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - elk
      - mail
    ports:
      - "8181:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://openloyalty:openloyalty@db:5432/openloyalty
      - SYMFONY_DEBUG=1
    volumes:
      - ./backend:/var/www/ol/backend
      - backend_vendor:/var/www/ol/backend/vendor
      - backend_cache:/var/www/ol/backend/var/cache
      - backend_logs:/var/www/ol/backend/var/logs
    networks:
      - openloyalty_network
    restart: unless-stopped
    command: >
      sh -c "composer install -o --prefer-dist &&
             bin/console cache:clear &&
             bin/console assets:install --symlink &&
             chown -R www-data:www-data /var/www/ol/backend/var &&
             chown -R www-data:www-data /var/www/ol/backend/app/uploads &&
             apache2-foreground"

  frontend:
    container_name: open_loyalty_frontend_dev
    build: ./frontend
    ports:
      - "8182:3000"
      - "8183:3001"
      - "8184:3002"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - openloyalty_network
    restart: unless-stopped

  db:
    container_name: open_loyalty_postgresql_dev
    image: postgres:17
    environment:
      - POSTGRES_DB=openloyalty
      - POSTGRES_USER=openloyalty
      - POSTGRES_PASSWORD=openloyalty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openloyalty_network
    restart: unless-stopped
    ports:
      - "5432:5432"

  pgadmin:
    container_name: open_loyalty_pgadmin_dev
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@openloyalty.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8889:80"
    networks:
      - openloyalty_network
    restart: unless-stopped
    depends_on:
      - db

  elk:
    container_name: open_loyalty_elasticsearch_dev
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - openloyalty_network
    restart: unless-stopped
    ports:
      - "9200:9200"

  mail:
    container_name: open_loyalty_mailhog_dev
    image: mailhog/mailhog:latest
    ports:
      - "8186:8025"
      - "8187:1025"
    networks:
      - openloyalty_network
    restart: unless-stopped

  redis:
    container_name: open_loyalty_redis_dev
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openloyalty_network
    restart: unless-stopped

networks:
  openloyalty_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  elasticsearch_data:
  redis_data:
  backend_vendor:
  backend_cache:
  backend_logs:
