# use as docker-compose -f docker-composer.yml -f docker-compose.test.yml up
backend:
  command: bash -c "composer install && bin/console assets:install --symlink && chown -R www-data:www-data /var/www/ol/backend/var && chown -R www-data:www-data /var/www/ol/backend/app/uploads && phing ci-setup-test"
